final Map<String, String> en = {
  'Profil': 'Profile',
  'Modifier': 'Edit',
  'Paramètres': 'Settings',
  'Mes_données_personnelles': 'My personal data',
  'Déconnexion': 'Logout',
  'Apprendre_le_code': 'Learn the code',
  'Série_n°_nb:': 'Series no:',
  'Règles_en_Route': 'Rules on the Road',
  'Sur_la_Voie_de_la_Sécurité': 'On the Road to Safety',
  'Les_Signaux_de_la_Route': 'Road Signs',
  'Conduite_Maitrisée': 'Mastered Driving',
  'Trouver_votre_Permis': 'Find your Permit',
  'Consulter_votre_calendrier': 'Check your calendar',
  'Restez_en_contact_en_laissant_un_message.': 'Stay in touch by leaving a message.',
  'Apprendre_votre_code': 'Learn your code',
  'Consulter_votre_historique_de_paiement': 'Check your payment history',
  'Bienvenue_au_PermitExpert': 'Welcome to PermitExpert',
  'Consulter_le_calendrier': 'Check the calendar',
  "Consulter_l'historique_de_paiement": "Check payment history",
  'Laisser_un_message': 'Leave a message',
  'Connexion': 'Log In',
  'Bienvenue_sur_Permit_Expert': 'Welcome to Permit Expert',
  'Email': 'Email',
  'Mot_de_passe': 'Password',
  'Mot_de_passe_oublié_?': 'Forgot Password?',
  'Se_Connecter': 'Log In',
  "Vous_n'avez_pas_de_compte_?": "Don't have an account?",
  "S'inscrire": "Sign Up",
  'Code_de_vérification': 'Verification Code',
  'Nous_avons_envoyé_le_code_de_vérification_à_votre_adresse_e-mail': 'We sent the verification code to your email address',
  'Continue': 'Continue',
  'Inscription': 'Registration',
  'Remplissez_le_formulaire_pour_continuer': 'Fill out the form to continue',
  'Nom_d\'utilisateur': 'Username',
  'Numéro_de_téléphone': 'Phone number',
  'Confirmer_votre_mot_de_passe': 'Confirm your password',
  'Vous_avez_déjà_un_compte_?': 'Already have an account?',
  'Se_connecter': 'Log In',
};
