import 'package:get/get_navigation/src/root/internacionalization.dart';

class Ar extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar': {
      'Profil': 'الملف الشخصي',
      'Modifier': 'تعديل',
      'Paramètres': 'الإعدادات',
      'Mes_données_personnelles': 'بياناتي الشخصية',
      'Déconnexion': 'تسجيل الخروج',
      'Apprendre_le_code': 'تعلم الكود',
      'Série_nb': 'السلسلة رقم :',
      'Règles_en_Route': 'قواعد الطريق',
      'Sur_la_Voie_de_la_Sécurité': 'على طريق السلامة',
      'Les_Signaux_de_la_Route': 'إشارات الطريق',
      'Conduite_Maitrisée': 'قيادة متقنة',
      'Trouver_votre_Permis': 'العثور على رخصتك',
      'Consulter_votre_calendrier': 'عرض جدولك الزمني',
      'Restez_en_contact_en_laissant_un_message.': 'ابق على تواصل بترك رسالة.',
      'Apprendre_votre_code': 'تعلم الكود الخاص بك',
      'Consulter_votre_historique_de_paiement': 'عرض تاريخ الدفع الخاص بك',
      'Bienvenue_au_PermitExpert': 'مرحبا بك في PermitExpert',
      'Consulter_le_calendrier': 'عرض التقويم',
      "Consulter_l'historique_de_paiement": "عرض تاريخ الدفع",
      'Laisser_un_message': 'ترك رسالة',
      'Connexion': 'تسجيل الدخول',
      'Bienvenue_sur_Permit_Expert': 'مرحبا بك في Permit Expert',
      'Email': 'البريد الإلكتروني',
      'Mot_de_passe_oublié_?': 'نسيت كلمة المرور ؟',
      'Se_Connecter': 'تسجيل الدخول',
      "Vous_n'avez_pas_de_compte_?": "ليس لديك حساب ؟",
      "S'inscrire": "التسجيل",
      'Code_de_vérification': 'رمز التحقق',
      'Nous_avons_envoyé_le_code_de_vérification_à_votre_adresse_e-mail': 'لقد أرسلنا رمز التحقق إلى بريدك الإلكتروني',
      'Continue': 'متابعة',
      'Inscription': 'التسجيل',
      'Remplissez_le_formulaire_pour_continuer': 'املأ النموذج للمتابعة',
      'Nom_d\'utilisateur': 'اسم المستخدم',
      'Numéro_de_téléphone': 'رقم الهاتف',
      'Mot_de_passe': 'كلمة المرور',
      'Confirmer_votre_mot_de_passe': 'تأكيد كلمة المرور',
      'Vous_avez_déjà_un_compte_?': 'هل لديك حساب بالفعل ؟',
      'Se_connecter': 'تسجيل الدخول',
      'Voici_une_ressource_qui_peut_vous_aider:': 'إليك مورد يمكن أن يساعدك:',
      'Voici_un_test_en_ligne_qui_peut_vous_aider:': 'إليك اختبارًا عبر الإنترنت يمكن أن يساعدك:',
      'Voici_quelques_vidéos_qui_peuvent_vous_aider:': 'إليك بعض مقاطع الفيديو التي يمكن أن تساعدك:',
      'Mode_nuit': 'الوضع الليلي',
      'Changer_mot_de_passe':'تغيير كلمة المرور',
      'Votre_calendrier':'جدولك الزمني',
      'Aucun_événement':'لا يوجد حدث',
      'Choisir_langage':'اختر اللغة',
      'Enregistrer': 'حفظ',
      'Envoyer': 'إرسال',
      'Votre_message_a_été_envoyé_avec_succès': 'تم إرسال رسالتك بنجاح',
      'Laisser_votre_message': 'اترك رسالتك',
      'Crédits': 'الائتمان',
      'Historique_de_paiement': 'سجل الدفع',
      'Paiement':'الدفع',
      'Aucune_transaction_disponible':'لا توجد معاملات متاحة',
      'Solde_Total':'الرصيد الإجمالي',
      'Débits':'مسحوبات',
      'Voir_Tous':'عرض الكل',
      'Notifications': 'الإشعارات',
      'Aucune_notification': 'لا توجد إشعارات',
      'Bienvenue sur Permit Expert': 'مرحبًا بك في خبير الترخيص',
      'Le champ_email_est_obligatoire': 'حقل البريد الإلكتروني مطلوب',
      'Veuillez_saisir_une_adresse_email_valide (@gmail.com)': 'يرجى إدخال عنوان بريد إلكتروني صالح (@gmail.com)',
      "Mot_de_passe_oublié ?": 'هل نسيت كلمة المرور؟',
      'Le_mot_de_passe_est_obligatoire': 'كلمة المرور مطلوبة',
      'Le_mot_de_passe_doit_avoir_plus_que_8_caracteres': 'يجب أن تحتوي كلمة المرور على أكثر من 8 أحرف',
      'Mot_de_passe_actuel:': 'كلمة المرور الحالية:',
      'Nouveau_mot_de_passe:': 'كلمة مرور جديدة:',
      'Confirmer_mot_de_passe:':'تأكيد كلمة المرور:',
      'Ce_champ_est_obligatoire':'هذا الحقل مطلوب',
      'Mot_de_passe_actuel': 'كلمة المرور الحالية:',
      'Nouveau_mot_de_passe': 'كلمة مرور جديدة:',
      'Confirmer_mot_de_passe':'تأكيد كلمة المرور:',
      'Réinitialisation_du_mot_de_passe': 'إعادة تعيين كلمة المرور',
      'Nouveau_Mot_de_passe': 'كلمة مرور جديدة',
      'Le_champ_nouveau_mot_de_passe_est_obligatoire': 'حقل كلمة المرور الجديدة مطلوب',
      'Le_champ_de_confirmation_du_mot_de_passe_est_obligatoire': 'حقل تأكيد كلمة المرور مطلوب',
      'Les_mots_de_passe_ne_correspondent_pas': 'كلمات المرور غير متطابقة',
      'Succès': 'نجاح',
      'Mot_de_passe_réinitialisé': 'تم إعادة تعيين كلمة المرور',
      'Le_code_de_vérification_est_correcte': 'رمز التحقق صحيح',
      'Le_code_doit_être_composé_de_4_chiffres': 'يجب أن يتكون الرمز من 4 أرقام',
      'Veuillez_remplir_tous_les_champs_du_code': 'يرجى ملء جميع حقول الرمز',
      'Continuer': 'متابعة',
      'Vous_avez_déjà_un_compte': 'هل لديك حساب بالفعل؟',







    },
  };
}
