import 'package:get/get.dart';


class Fr extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
  'fr': {
  'Profil': 'Profil',
  'Modifier': 'Modifier',
  'Paramètres': 'Paramètres',
  'Mes_données_personnelles': 'Mes données personnelles',
  'Déconnexion': 'Déconnexion',
  'Apprendre_le_code': 'Apprendre le code',
  'Série_nb': 'Série n° :',
  'Règles_en_Route': 'Règles en Route',
  'Sur_la_Voie_de_la_Sécurité': 'Sur la Voie de la Sécurité',
  'Les_Signaux_de_la_Route': 'Les Signaux de la Route',
  'Conduite_Maitrisée': 'Conduite Maitrisée',
  'Trouver_votre_Permis': 'Trouver votre Permis',
  'Consulter_votre_calendrier': 'Consulter votre calendrier',
  'Restez_en_contact_en_laissant_un_message.': 'Restez en contact en laissant un message.',
  'Apprendre_votre_code': 'Apprendre votre code',
  'Consulter_votre_historique_de_paiement': 'Consulter votre historique de paiement',
  'Bienvenue_au_PermitExpert': 'Bienvenue au PermitExpert',
  'Consulter_le_calendrier': 'Consulter  le calendrier',
  "Consulter_l'historique_de_paiement": "Consulter l'historique de paiement",
  'Laisser_un_message': 'Laisser un message',
  'Connexion': 'Connexion',
  'Bienvenue_sur_Permit_Expert': 'Bienvenue sur Permit Expert',
  'Email': 'Email',
  'Mot_de_passe_oublié_?': 'Mot de passe oublié ?',
  'Se_Connecter': 'Se Connecter',
  "Vous_n'avez_pas_de_compte_?": "Vous n'avez pas de compte ?",
  "S'inscrire": "S'inscrire",
  'Code_de_vérification': 'Code de vérification',
  'Nous_avons_envoyé_le_code_de_vérification_à_votre_adresse_e-mail': 'Nous avons envoyé le code de vérification à votre adresse e-mail',
  'Continue': 'Continue',
  'Inscription': 'Inscription',
  'Remplissez_le_formulaire_pour_continuer': 'Remplissez le formulaire pour continuer',
  'Nom_d\'utilisateur': 'Nom d\'utilisateur',
  'Numéro_de_téléphone': 'Numéro de téléphone',
  'Mot_de_passe': 'Mot de passe',
  'Confirmer_votre_mot_de_passe': 'Confirmer votre mot de passe',
  'Vous_avez_déjà_un_compte_?': 'Vous avez déjà un compte ?',
  'Se_connecter': 'Se connecter',
  'Voici_une_ressource_qui_peut_vous_aider:': 'Voici une ressource qui peut vous aider:',
  'Voici_un_test_en_ligne_qui_peut_vous_aider:': 'Voici un test en ligne qui peut vous aider:',
  'Voici_quelques_vidéos_qui_peuvent_vous_aider:': 'Voici quelques vidéos qui peuvent vous aider:',
    'Mode_nuit': 'Mode nuit',
    'Changer_mot_de_passe':'Changer mot de passe',
    'Votre_calendrier':'Votre calendrier',
    'Aucun_événement':'Aucun événement',
    'Choisir_langage':'choisir langage',
    'Enregistrer':'Enregistrer',
    'Envoyer':'Envoyer',
    'Votre_message_a_été_envoyé_avec_succès':'Votre message a été envoyé avec succès',
    'Laisser_votre_message': 'Laisser votre message',
    'Crédits': 'Crédits',
    'Voir_Tous':'Voir Tous',
    'Aucune_notification':'Aucune notification',
    "Mot_de_passe_oublié ?": 'Mot de passe oublié ?',
    'Réinitialisation_du_mot_de_passe': 'Réinitialisation du mot de passe',
    'Nouveau_Mot_de_passe': 'Nouveau Mot de passe',
    'Le_champ_nouveau_mot_de_passe_est_obligatoire': 'Le champ nouveau mot de passe est obligatoire',
    'Le_champ_de_confirmation_du_mot_de_passe_est_obligatoire': 'Le champ de confirmation du mot de passe est obligatoire',
    'Les_mots_de_passe_ne_correspondent_pas': 'Les mots de passe ne correspondent pas',
    'Succès': 'Succès',
    'Mot_de_passe_réinitialisé': 'Mot de passe réinitialisé',
    'Le_code_de_vérification_est_correcte': 'Le code de vérification est correcte',
    'Le_code_doit_être_composé_de_4_chiffres': 'Le code doit être composé de 4 chiffres',
    'Veuillez_remplir_tous_les_champs_du_code': 'Veuillez remplir tous les champs du code',
    'Continuer': 'Continuer',
    'Vous_avez_déjà_un_compte': 'Vous avez déjà un compte ?',
    'Historique_de_paiement':'Historique de paiement',
    'Solde_Total':'Solde Total',
    'Nouveau_Mot_de_passe':'Nouveau_Mot_de_passe',

  },
  };
}