
final Map<String, String> fr = {
  'Profil': 'Profil',
  'Modifier': 'Modifier',
  'Paramètres': 'Paramètres',
  'Mes_données_personnelles': 'Mes données personnelles',
  'Déconnexion': 'Déconnexion',
  'Apprendre_le_code': 'Apprendre le code',
  'Série_n°_nb:': 'Série n° :',
  'Règles_en_Route': 'Règles en Route',
  'Sur_la_Voie_de_la_Sécurité': 'Sur la Voie de la Sécurité',
  'Les_Signaux_de_la_Route': 'Les Signaux de la Route',
  'Conduite_Maitrisée': 'Conduite Maitrisée',
  'Trouver_votre_Permis': 'Trouver votre Permis',
  'Consulter_votre_calendrier': 'Consulter votre calendrier',
  'Restez_en_contact_en_laissant_un_message.': 'Restez en contact en laissant un message.',
  'Apprendre_votre_code': 'Apprendre votre code',
  'Consulter_votre_historique_de_paiement': 'Consulter votre historique de paiement',
  'Bienvenue_au_PermitExpert': 'Bienvenue au PermitExpert',
  'Consulter_le_calendrier': 'Consulter  le calendrier',
  "Consulter_l'historique_de_paiement": "Consulter l'historique de paiement",
  'Laisser_un_message': 'Laisser un message',
  'Connexion': 'Connexion',
  'Bienvenue_sur_Permit_Expert': 'Bienvenue sur Permit Expert',
  'Email': 'Email',
  'Mot_de_passe_oublié_?': 'Mot de passe oublié ?',
  'Se_Connecter': 'Se Connecter',
  "Vous_n'avez_pas_de_compte_?": "Vous n'avez pas de compte ?",
  "S'inscrire": "S'inscrire",
  'Code_de_vérification': 'Code de vérification',
  'Nous_avons_envoyé_le_code_de_vérification_à_votre_adresse_e-mail': 'Nous avons envoyé le code de vérification à votre adresse e-mail',
  'Continue': 'Continue',
  'Inscription': 'Inscription',
  'Remplissez_le_formulaire_pour_continuer': 'Remplissez le formulaire pour continuer',
  'Nom_d\'utilisateur': 'Nom d\'utilisateur',
  'Numéro_de_téléphone': 'Numéro de téléphone',
  'Mot_de_passe': 'Mot de passe',
  'Confirmer_votre_mot_de_passe': 'Confirmer votre mot de passe',
  'Vous_avez_déjà_un_compte_?': 'Vous avez déjà un compte ?',
  'Se_connecter': 'Se connecter',


};